# **PyTorch Fundamentals Exercise**



In [1]:
import torch
import numpy as np

### **Q1 Create a random tensor with shape `(7, 7)`**


In [2]:
tensor_7x7 = torch.rand(7, 7)
tensor_7x7, tensor_7x7.shape

(tensor([[0.6541, 0.3190, 0.0809, 0.9066, 0.6222, 0.9046, 0.7074],
         [0.4280, 0.4748, 0.0854, 0.4643, 0.3773, 0.4378, 0.2141],
         [0.8913, 0.3232, 0.7374, 0.4492, 0.1618, 0.9518, 0.1621],
         [0.5853, 0.0541, 0.7013, 0.5379, 0.0466, 0.2038, 0.6059],
         [0.4947, 0.2242, 0.3542, 0.2801, 0.0718, 0.2801, 0.6410],
         [0.6597, 0.8617, 0.2675, 0.9112, 0.4741, 0.9575, 0.7615],
         [0.5840, 0.8938, 0.9149, 0.6207, 0.2142, 0.1712, 0.7041]]),
 torch.Size([7, 7]))

### **Q2 Perform a matrix multiplication on the tensor from Q1 with another random tensor with shape `(1, 7)`**

In [3]:
tensor_1x7 = torch.rand(1, 7)
matmul_result = torch.matmul(tensor_7x7, tensor_1x7.T)  # transpose required
matmul_result, matmul_result.shape  # -> (7, 1)

(tensor([[1.9246],
         [1.1853],
         [1.2614],
         [0.8694],
         [0.7847],
         [2.0893],
         [1.5011]]),
 torch.Size([7, 1]))

### **Q3 Set the random seed to `0` and do Q1 & Q2 over again**

In [4]:
torch.manual_seed(0)
tensor_7x7 = torch.rand(7, 7)
tensor_1x7 = torch.rand(1, 7)
matmul_result = torch.matmul(tensor_7x7, tensor_1x7.T)
matmul_result, matmul_result.shape
# Expected: tensor([[1.8542], [1.9611], [2.2884], ...]) shape (7, 1)

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### **Q4 Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent?**
  * If there is, set the GPU random seed to `1234`

In [5]:
torch.cuda.manual_seed(1234)


### **Q5 Create two random tensors of shape `(2, 3)` and send them both to the GPU. Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed)**

In [6]:
torch.manual_seed(1234)
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

tensor_a = torch.rand(2, 3).to(device)
tensor_b = torch.rand(2, 3).to(device)
tensor_a, tensor_b

Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### **Q6 Perform a matrix multiplication on the tensors you created in Q5**

In [7]:
tensor_c = torch.matmul(tensor_a, tensor_b.T)  # (2,3) @ (3,2) -> (2,2)
tensor_c, tensor_c.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### **Q7 Find the maximum and minimum values of the output of Q6**

In [8]:
max_val = torch.max(tensor_c)
min_val = torch.min(tensor_c)
max_val, min_val

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

### **Q8 Find the index of the maximum and minimum values of the output of Q6**

In [9]:
arg_max = torch.argmax(tensor_c)
arg_min = torch.argmin(tensor_c)
arg_max, arg_min

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))

### **Q9 Perform a matrix multiplication on the tensors you created in Q5 in `numpy` and convert the output to tensor**

In [10]:
arg_max = torch.argmax(tensor_c)
arg_min = torch.argmin(tensor_c)
arg_max, arg_min

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### **Q10 Make a random tensor with shape `(1, 1, 1, 10)` and then convert it to a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape**

In [11]:
torch.manual_seed(7)
tensor_d = torch.rand(1, 1, 1, 10)
tensor_e = tensor_d.squeeze()

print(tensor_d, tensor_d.shape)
print(tensor_e, tensor_e.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
